### ISSUE TITLE
Some suggestions for readme. 

### ISSUE THREAD

**Issue by rocket-pig** [JevinJ/Bittrex-Notify#1]
Just some suggestions for what to include in the readme:

This project is aimed at python3.x, python2.x will be difficult if not impossible to use

Requires tkinter, which is not a pip-installable package. On Debian/Ubuntu:
sudo apt install python3-tk

Requires 'certifi', which _is a pip-installable package:
sudo -H pip3 install certifi

Requires 'urllib3', which _is a pip-installable package:
sudo -H pip3 install urllib3

To start:
python3 main.py 

------------------------------------------------------

At which point, for me, the tk window appears, the bottom-right countdown counts from 15 to 1, then an error prints in console: 
"
 File "/home/user/projects/Bittrex-Notify/src/fasttick.py", line 35, in heartbeat
    data = json.loads(page)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
"

No data of any kind is shown in window. The bottom-right countdown stays at 1, while the larger top-right countdown continues. 

I'll try experimenting. Nice-looking project so far though! Thanks for sharing and I hope my input was useful.

**Comment by JevinJ** [comment]
Thanks, I haven't had a day where I can work on documentation for this project. I'm hoping to do some finishing up/polishing in the coming days. For the json bug, it _appears_ to be related to something happening on the Bittrex API side, I've encountered it myself but haven't been able to reproduce it. Just restarting fixes it for me. I'll also try this out on raspbian so I can work out issues on linux.

**Comment by JevinJ** [comment]
README and most documentation is done for windows Python3 at least, I'll be looking at Linux and Python 2.x next.
