### ISSUE TITLE
UTf-8 encoding problems w urllib3 response

### ISSUE THREAD

**Issue by rocket-pig** [JevinJ/Bittrex-Notify#2]
I can't remember the error from before now, something like 'response must be string, not bytes'. I don't know why this is an issue on my machine and not on OP/JevinJ's. But here is how I fixed it:

in 'fasttick.py' in the 'heartbeat()' function, I deleted use of urllib3 and replaced with:

from urllib.request import urlopen
def heartbeat():
    response = urlopen('https://bittrex.com/api/v2.0/pub/Markets/GetMarketSummaries').read().decode('utf8')
    data = json.loads(response)

This brought me to the next error, pickle's attempt to write to a directory 'fast_history' that doesnt exist.
mkdir fast_history
fixed that. I got one screen update that showed three or four markets, but since then, the screen is blank after each 15 second loop. The fast_history folder is filling up with .pickle files though.

**Comment by rocket-pig** [comment]
Here we go. I'm still relatively new to github, but I made a fork with described changes here: 
https://github.com/JevinJ/Bittrex-Notify/compare/master...rocket-pig:master

**Comment by JevinJ** [comment]
@rocket-pig Good work, this is something I've encountered but usually goes away when I restart. I can merge the two if you like.

The screen being blank may be normal if the market is slow at the time, you can test this by changing line 67 of the current version(if average_rate >= MIN_RATE:) to (if True:) and it should fill up completely.

**Comment by JevinJ** [comment]
This should be fixed now.
